helix-bridge/helix-ui

.github/workflows/deploy-dev.yml, package.json
=> build: add lint process to ci

package.json, packages/helix/.env.production, packages/helix/package.json
=> build: update pro endpoint

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml
=> Fix release ci

packages/helix/components/transaction/Record.tsx, packages/helix/pages/transaction/[id].tsx, packages/helix/pages/transaction/index.tsx
=> fix(#23): loading aborted

packages/apps/components/form-control/BridgeSelector.tsx, packages/apps/components/form-control/RecipientItem.tsx, packages/apps/components/tx/TransferConfirm.tsx, packages/apps/hooks/tx.tsx, packages/shared/components/widget/IdentAccountAddress.tsx
=> fix: recipient component and transfer confirm symbol

package.json, packages/apps/bridges/ethereum-darwinia/Claim.tsx, packages/apps/components/record/HistoryItem.tsx, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/hooks/allowance.tsx, packages/apps/pages/_app.tsx, packages/apps/providers/index.ts, packages/apps/providers/wallet.tsx
=> fix: allowance wrong network

.github/workflows/test.yml
=> ci: notification err

packages/apps/bridges/substrate-substrateDVM/utils/tx.ts, packages/apps/components/CrossChain.tsx, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts, packages/shared/config/network/pangolin.ts
crab 1221 pangolin: 28110 pangoro: 28110
=> chore: bump spec version

packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts
=> Bump crab spec

packages/apps/CHANGELOG.md, packages/apps/package.json, packages/helix/CHANGELOG.md, packages/helix/package.json, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts
=> bump crab spec and release

packages/apps/bridges/substrate-substrateDVM/utils/fee.ts, packages/apps/bridges/substrate-substrateDVM/utils/tx.ts
=> chore: update s2s fee method

packages/apps/bridges/substrate-substrateDVM/utils/fee.ts, packages/apps/bridges/substrate-substrateDVM/utils/tx.ts
It will break when Darwinia update
=> chore: s2s fee revert

packages/shared/config/network/darwinia.ts
=> chore: bump darwinia spec

packages/shared/config/network/ethereum.ts
=> fix: decimal for ring on eth

.github/workflows/test.yml, package.json, packages/apps/bridges/ethereum-darwinia/Darwinia2Ethereum.tsx, packages/apps/bridges/ethereum-darwinia/Ethereum2Darwinia.tsx, packages/apps/bridges/ethereum-darwinia/utils/tx.ts, packages/apps/bridges/substrate-dvm/DVM2Substrate.tsx, packages/apps/bridges/substrate-dvm/Substrate2DVM.tsx, packages/apps/bridges/substrate-dvm/utils/tx.ts, packages/apps/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx, packages/apps/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx, packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/hooks/tx.tsx, packages/apps/providers/tx.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/apps/utils/balance.ts, packages/apps/utils/index.ts, packages/shared/config/network/ethereum.ts, packages/shared/model/bridge/cross-chain.ts, packages/shared/package.json, packages/shared/utils/helper/common.ts, packages/shared/utils/tx/common.tsx, packages/shared/utils/tx/sendExtrinsic.ts
=> refactor: balance fetching and refresh move to upper level component

packages/apps/bridges/ethereum-darwinia/Ethereum2DarwiniaHistory.tsx
=> fix(#55): eth to darwinia record status error

packages/helix/components/AppLayout.tsx, packages/helix/package.json, packages/helix/pages/transaction/index.tsx, packages/helix/public/locales/en/common.json, packages/helix/public/locales/zh/common.json, packages/helix/styles/index.scss, packages/helix/tailwind.config.js
=> feat: replace virtual scroll with pagination

packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro.ts, packages/shared/model/network/config.ts
=> chore: bump test chain spec version

packages/apps/components/CrossChain.tsx, packages/apps/components/Footer.tsx, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/components/widget/account/SelectAccountModal.tsx, packages/apps/components/widget/account/SelectWalletModal.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/helix/components/transaction/ViewBoard.tsx, packages/helix/pages/transaction/index.tsx
=> fix: some known issue

.github/workflows/deploy-prd.yml
=> Deploy apps-test for prod mode

packages/apps/bridges/parachain-substrate/Parachain2Substrate.tsx, packages/apps/bridges/parachain-substrate/utils/fee.ts, packages/apps/bridges/parachain-substrate/utils/tx.ts
=> fix: parachain fee

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml, .github/workflows/deploy-stg.yml
=> ci: helix test chain deployment

packages/helix/pages/transaction/index.tsx
=> fix(#79): checksum account can not find records

packages/helix/pages/transaction/s2s/[id].tsx
=> fix(#75): target hash

packages/apps/bridges/parachain-substrate/Parachain2Substrate.tsx, packages/apps/bridges/parachain-substrate/Substrate2Parachain.tsx, packages/apps/bridges/parachain-substrate/index.ts, packages/apps/bridges/register.tsx, packages/shared/__tests__/components/SubscanLink.spec.tsx, packages/shared/components/widget/SubscanLink.tsx, packages/shared/config/network/pangolin-parachain.ts
Update SubscanLink tests to cover all chain links
=> chore: bump pangolin-parachain spec version

packages/helix/__tests__/components/TargetTx.spec.tsx, packages/helix/__tests__/components/TxStatus.spec.tsx, packages/helix/__tests__/components/__snapshots__/SourceTx.spec.tsx.snap, packages/helix/__tests__/components/__snapshots__/TargetTx.spec.tsx.snap, packages/helix/__tests__/components/__snapshots__/Timestamp.spec.tsx.snap, packages/helix/__tests__/components/__snapshots__/TxStatus.spec.tsx.snap, packages/helix/components/transaction/Detail.tsx, packages/helix/components/transaction/TargetTx.tsx, packages/helix/components/transaction/TransferDescription.tsx, packages/helix/components/transaction/TransferDetail.tsx, packages/helix/components/transaction/TxStatus.tsx, packages/helix/config/gql.ts, packages/helix/model/transfer.ts, packages/helix/pages/index.tsx, packages/helix/pages/transaction/index.tsx, packages/helix/pages/transaction/s2dvm/[id].tsx, packages/helix/pages/transaction/s2parachain/[id].tsx, packages/helix/pages/transaction/s2s/[id].tsx, packages/shared/components/widget/CrossChainStatus.tsx, packages/shared/config/network/crab-parachain.ts, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin-parachain.ts, packages/shared/config/network/polygon.ts, packages/shared/model/aggregation-api/statistics.ts
=> fix: target tx hash

packages/apps/bridges/ethereum-darwinia/utils/tx.ts
=> fix: e2d transfer amount sub fee

packages/apps/bridges/ethereum-darwinia/Ethereum2Darwinia.tsx, packages/apps/components/CrossChain.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json
=> fix(#90): e2d allowance

packages/helix/pages/transaction/s2dvm/[id].tsx
=> chore: fix dvm precision

packages/helix/pages/transaction/s2dvm/[id].tsx
=> fix: revert dvm detial code

packages/helix/pages/index.tsx, packages/helix/pages/transaction/index.tsx
=> chore: force fetch data

.github/workflows/deploy-prd.yml
=> ci: update test chain ci

packages/apps/components/form-control/BridgeSelector.tsx, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab-parachain.ts, packages/shared/config/network/crab.ts
=> chore: bump crab spec version 1230

packages/apps/bridges/ethereum-darwinia/Darwinia2EthereumHistory.tsx, packages/apps/bridges/ethereum-darwinia/Ethereum2DarwiniaHistory.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json
=> fix(#100): eth darwina finish link

packages/apps/CHANGELOG.md, packages/apps/bridges/ethereum-darwinia/Darwinia2Ethereum.tsx, packages/apps/bridges/ethereum-darwinia/Ethereum2Darwinia.tsx, packages/apps/bridges/ethereum-darwinia/utils/tx.ts, packages/apps/bridges/parachain-substrate/Parachain2Substrate.tsx, packages/apps/bridges/parachain-substrate/Substrate2Parachain.tsx, packages/apps/bridges/parachain-substrate/utils/fee.ts, packages/apps/bridges/parachain-substrate/utils/tx.ts, packages/apps/bridges/substrate-dvm/DVM2Substrate.tsx, packages/apps/bridges/substrate-dvm/Substrate2DVM.tsx, packages/apps/bridges/substrate-dvm/utils/tx.ts, packages/apps/bridges/substrate-substrateDVM/Substrate2SubstrateDVM.tsx, packages/apps/bridges/substrate-substrateDVM/SubstrateDVM2Substrate.tsx, packages/apps/bridges/substrate-substrateDVM/utils/tx.ts, packages/apps/config/validation.ts, packages/apps/model/index.ts, packages/apps/model/validation.ts, packages/apps/package.json, packages/apps/utils/tx.ts, packages/shared/__tests__/network.spec.ts, packages/shared/config/bridge.ts
add crab parachain
optimize tx creating process
=> feat: crab parachain

packages/apps/components/form-control/BridgeSelector.tsx, packages/apps/components/form-control/SelectTokenModal.tsx, packages/shared/config/bridges/parachain-substrate.ts, packages/shared/model/bridge/bridge.ts
=> chore: forbidden parachain to crab

packages/helix/__tests__/components/Timestamp.spec.tsx, packages/helix/__tests__/components/__snapshots__/Timestamp.spec.tsx.snap, packages/helix/components/transaction/Timestamp.tsx, packages/helix/package.json, packages/shared/components/widget/ThemeSwitch.tsx, packages/shared/config/network/darwinia.ts, packages/shared/config/network/pangoro.ts, packages/shared/utils/bridge/bridge.ts
=> chore: bump darwinia spec version

packages/apps/jest.config.js, packages/helix/__tests__/components/TargetTx.spec.tsx, packages/helix/__tests__/components/TxStatus.spec.tsx, packages/helix/__tests__/components/__snapshots__/TargetTx.spec.tsx.snap, packages/helix/__tests__/components/__snapshots__/TxStatus.spec.tsx.snap, packages/helix/components/transaction/TargetTx.tsx, packages/helix/components/transaction/TxStatus.tsx, packages/helix/jest.config.js
100% coverage of helix component tests
=> test: update tests

packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts
=> chore: spec version

packages/apps/bridges/cBridge/CBridge.tsx
=> chore: ring name

packages/shared/utils/record/record.ts
=> chore: eth polygon heco precison

packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts
=> chore: bump crab spec version

packages/apps/bridges/substrateDVM-substrateDVM/SubstrateDVM2SubstrateDVM.tsx, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro-dvm.ts, packages/shared/config/network/pangoro.ts
=> chore: bump pangolin & pangoro spec version

packages/shared/config/bridges/parachain-substrate.ts
=> feat: allow parachain to crab

packages/apps/bridges/cBridge/CBridge.tsx, packages/apps/bridges/ethereum-darwinia/Ethereum2Darwinia.tsx, packages/apps/components/CrossChain.tsx, packages/apps/hooks/allowance.tsx, packages/shared/model/bridge/cross-chain.ts, packages/shared/utils/tx/common.tsx
=> fix: polygon approve

packages/apps/bridges/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/components/history/PendingToRefund.tsx, packages/apps/styles/index.scss
=> feat: pangolin  pangoro refund

packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro-dvm.ts, packages/shared/config/network/pangoro.ts, packages/shared/utils/network/balance/darwinia.ts
=> fix: use available balance instead of total balance

packages/shared/components/widget/TxStatus.tsx, packages/shared/utils/mmr/mmr.ts
=> fix: d2e claim api error

packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/providers/account.tsx
=> fix: memory lastest selected polkadot account

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/components/widget/CountLoading.tsx, packages/apps/styles/index.scss, packages/apps/styles/loading.scss
=> feat(#88): refresh balance

packages/apps/components/AppLayout.tsx, packages/apps/pages/index.tsx, packages/shared/model/storage.ts
=> chore: dismiss disclaimer

packages/apps/providers/claim.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json
=> fix: add allowance validation before claim

packages/helix/components/dashboard/Statistics.tsx, packages/helix/components/transaction/Bridge.tsx, packages/helix/config/gql.ts, packages/helix/pages/index.tsx, packages/helix/pages/transaction/index.tsx, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro-dvm.ts, packages/shared/config/network/pangoro.ts, packages/shared/utils/network/network.ts
=> feat: bridge transactiion statistics

packages/apps/components/form-control/BridgeSelector.tsx, packages/helix/__tests__/components/TargetTx.spec.tsx, packages/shared/__tests__/bridge.spec.ts, packages/shared/__tests__/components/Footer.spec.tsx, packages/shared/__tests__/components/Navigator.spec.tsx, packages/shared/__tests__/components/__snapshots__/Navigator.spec.tsx.snap, packages/shared/__tests__/network.spec.ts, packages/shared/components/Footer.tsx, packages/shared/components/Navigator.tsx, packages/shared/config/network/bsc.ts, packages/shared/config/network/pangolin-dvm.ts, packages/shared/utils/bridge/bridge.ts
=> test: prefect unit test for shared package

packages/apps/bridges/cBridge/CBridge.tsx
=> fix(#183): fee precision on cBridge

packages/helix/components/transaction/Breadcrumb.tsx, packages/helix/components/transaction/Detail.tsx, packages/helix/hooks/updatableRecord.ts, packages/helix/pages/transaction/cbridge/[id].tsx, packages/helix/pages/transaction/s2dvm/[id].tsx, packages/helix/pages/transaction/s2parachain/[id].tsx, packages/helix/pages/transaction/s2s/[id].tsx, packages/helix/pages/transaction/xcm/[id].tsx, packages/helix/utils/getServerSideRecordProps.ts
=> chore: record detail loading strategy changed

packages/apps/__tests__/token.spec.ts, packages/apps/components/form-control/SelectTokenModal.tsx, packages/apps/components/history/History.tsx, packages/apps/utils/token.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia.ts, packages/shared/model/network/config.ts
=> chore: xRING rename to classic

packages/apps/bridge.sh, packages/apps/bridges/celer/cBridge/CBridge.tsx, packages/apps/components/form-control/BridgeSelector.tsx
=> chore: update bridge generator

packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/providers/claim.tsx, packages/apps/utils/balance.ts, packages/shared/config/bridges/substrateDVM-substrateDVM.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia-dvm.ts
=> support s2s

packages/shared/config/bridges/substrateDVM-substrateDVM.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia-dvm.ts
=> chore: update s2s v2 address

packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/fee.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/components/history/PendingToRefund.tsx, packages/apps/config/gql.ts, packages/shared/model/helix-indexer/record.ts
=> fix s2s refund

packages/apps/utils/records.ts, packages/shared/config/network/ethereum.ts
=> fix(#204): ethereum ring kton precision changed

packages/shared/config/network/arbitrum.ts, packages/shared/config/network/astar.ts, packages/shared/config/network/avalanche.ts, packages/shared/config/network/bsc.ts, packages/shared/config/network/ethereum.ts, packages/shared/config/network/optimism.ts, packages/shared/config/network/polygon.ts
=> fix(#203): avalanche stablecoin symbol rename

packages/apps/bridges/celer/cBridge/CBridge.tsx, packages/apps/bridges/celer/cBridge/hooks/transfer.ts
=> fix: avalanche symbol name for estimate amount

packages/apps/components/form-control/BridgeSelector.tsx, packages/shared/config/env.ts
=> feat: stg deployment recognizable

.github/workflows/deploy-stg.yml
=> Add manually deploy for stage deployment

packages/shared/config/env.ts, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro-dvm.ts, packages/shared/config/network/pangoro.ts
=> chore: predicate production deployment

packages/shared/config/bridges/polygon-astar.ts, packages/shared/model/bridge/polygon-astar.ts
=> chore: field name

packages/apps/__tests__/token.spec.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVMInner.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/config/wring.json, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/shared/__tests__/bridge.spec.ts, packages/shared/__tests__/network.spec.ts, packages/shared/config/bridges/substrateDVM-substrateDVM.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia.ts, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangoro.ts, packages/shared/configs.json, packages/shared/model/network/config.ts, packages/shared/utils/network/network.ts
close #224
RING<>wRING transferable
=> feat: deprecated bridge could be remove safely

packages/shared/config/bridges/crabDVM-ethereum.ts, packages/shared/config/bridges/ethereum-arbitrum.ts, packages/shared/config/bridges/ethereum-astar.ts, packages/shared/config/bridges/ethereum-avalanche.ts, packages/shared/config/bridges/ethereum-bsc.ts, packages/shared/config/bridges/ethereum-optimism.ts, packages/shared/config/bridges/ethereum-polygon.ts
=> update cbridge OriginalTokenVault address

packages/apps/bridges/celer/cBridge/CBridge.tsx, packages/apps/bridges/celer/cBridge/hooks/transfer.ts
=> fix: cBrdige burn deposit address

packages/apps/bridges/celer/cBridge/CBridge.tsx
=> fix: slippage not needed on peddged tx

packages/shared/config/network/crab-dvm.ts
=> chore: rename wckton to ckton

packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/fee.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts
=> update crab spec version

packages/apps/pages/_document.tsx
=> fix: page fouc caused by tailwind dark mode

packages/apps/bridges/celer/cBridge/hooks/transfer.ts, packages/apps/cypress/integration/dvm2Substrate.spec.ts, packages/shared/config/bridges/bsc-astar.ts, packages/shared/model/bridge/bridge.ts, packages/shared/model/bridge/bsc-astar.ts
=> fix(#241): busd contract address

packages/apps/components/form-control/SelectTokenModal.tsx
=> chore: xRING classic forbidden

packages/shared/config/network/crab-parachain.ts
=> chore: bump crab-parachain 5320

packages/apps/bridges/helix/ethereum-darwinia/utils/tx.ts
=> fix: e2d issue

packages/apps/components/NetworkG6.tsx, packages/apps/components/form-control/SelectTokenModal.tsx, packages/apps/utils/token.ts
=> feat: refact token selection

packages/apps/bridges/helix/substrate-substrateDVM/utils/dailyLimit.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVM2SubstrateDVM.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/dailyLimit.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/fee.ts, packages/apps/providers/wallet.tsx, packages/shared/utils/connection/connection.tsx
=> fix: s2s v2 fee & dailylimit error before wallet connected

packages/apps/bridges/celer/cBridge/utils/tx.ts, packages/apps/bridges/helix/substrate-substrateDVM/utils/tx.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/components/history/History.tsx, packages/shared/config/network/darwinia-dvm.ts, packages/shared/config/network/darwinia.ts
=> chore: bump darwinia 1241

packages/apps/bridges/celer/cBridge/utils/tx.ts, packages/apps/bridges/celer/ethereum-arbitrum/config/bridge.ts, packages/apps/bridges/celer/ethereum-astar/config/bridge.ts, packages/apps/bridges/celer/ethereum-avalanche/config/bridge.ts, packages/apps/bridges/celer/ethereum-bsc/config/bridge.ts, packages/apps/bridges/celer/ethereum-heco/config/bridge.ts, packages/apps/bridges/celer/ethereum-optimism/config/bridge.ts, packages/apps/bridges/celer/ethereum-polygon/config/bridge.ts, packages/apps/bridges/index.ts, packages/apps/components/form-control/BridgeSelector.tsx, packages/apps/model/validation.ts, packages/shared/model/bridge/bridge.ts
=> chore: restore stablecoin

packages/shared/config/network/darwinia-dvm.ts, packages/shared/config/network/darwinia.ts
=> chore: bumpt darwinia spec 1242

packages/shared/config/network/crab-parachain.ts
=> chore: bump crab-parachain spec 5330

packages/apps/__tests__/components/__snapshots__/Bridge.spec.tsx.snap, packages/apps/__tests__/components/__snapshots__/ViewBoard.spec.tsx.snap, packages/apps/components/CrossChain.tsx, packages/apps/components/NetworkG6.tsx, packages/apps/components/dashboard/Chain.tsx, packages/apps/components/dashboard/Statistics.tsx, packages/apps/components/history/History.tsx, packages/apps/components/transaction/Bridge.tsx, packages/apps/components/transaction/Detail.tsx, packages/apps/components/transaction/ViewBoard.tsx, packages/shared/components/Footer.tsx
=> fix(#248): remove all light tailwind cls

.eslintrc.js, packages/apps/bridges/helix/ethereum-darwinia/utils/tx.ts, packages/apps/config/constant.ts, packages/shared/config/network/arbitrum.ts, packages/shared/config/network/astar.ts, packages/shared/config/network/bsc.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab-parachain.ts, packages/shared/config/network/crab.ts, packages/shared/config/network/darwinia-dvm.ts, packages/shared/config/network/darwinia.ts, packages/shared/config/network/ethereum.ts, packages/shared/config/network/heco.ts, packages/shared/config/network/karura.ts, packages/shared/config/network/moonriver.ts, packages/shared/config/network/optimism.ts, packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin-parachain.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro.ts, packages/shared/config/network/polygon.ts, packages/shared/config/network/ropsten.ts, packages/shared/model/account.ts, packages/shared/utils/helper/common.ts
=> refactor: replace all providers with https

packages/apps/components/history/History.tsx
=> fix(#253): e2d has no detial page

packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVM2SubstrateDVM.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/model/validation.ts, packages/apps/utils/balance.ts, packages/apps/utils/bridge/bridge.ts, packages/shared/config/network/crab-parachain.ts, packages/shared/config/network/crab.ts, packages/shared/config/network/darwinia.ts, packages/shared/config/network/karura.ts, packages/shared/config/network/pangolin-parachain.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro.ts, packages/shared/utils/tx/common.tsx
=> fix: s2s v2 fee token validation

packages/shared/utils/connection/entrance.ts
=> chore: only store ws provider

packages/apps/bridges/helix/ethereum-darwinia/Darwinia2Ethereum.tsx, packages/apps/bridges/helix/ethereum-darwinia/utils/tx.ts
=> fix d2e fee

packages/apps/bridges/helix/ethereum-darwinia/Ethereum2Darwinia.tsx
=> fix: e2d allowance check ring only

packages/apps/bridges/helix/substrate-substrateDVM/Substrate2SubstrateDVM.tsx, packages/apps/bridges/helix/substrate-substrateParachain/Parachain2Substrate.tsx, packages/apps/bridges/helix/substrate-substrateParachain/Substrate2Parachain.tsx, packages/apps/bridges/helix/substrateDVM-ethereum/Ethereum2SubstrateDVM.tsx, packages/apps/bridges/helix/substrateDVM-ethereum/SubstrateDVM2Ethereum.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVM2SubstrateDVM.tsx, packages/shared/utils/tx/common.tsx
=> fix(#272): empty fee bug before tx launched

packages/apps/bridges/helix/substrateDVM-ethereum/config/bridge.ts, packages/apps/bridges/helix/substrateDVM-ethereum/utils/tx.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVM2SubstrateDVM.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/SubstrateDVMInner.tsx, packages/apps/bridges/helix/substrateDVM-substrateDVM/config/bridge.ts, packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/tx.ts, packages/apps/components/CrossChain.tsx, packages/apps/components/NetworkG6.tsx, packages/apps/components/bridge/BridgeArrow.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/components/history/History.tsx, packages/apps/components/widget/TokenOnChain.tsx, packages/apps/pages/index.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/shared/config/constant.ts, packages/shared/config/network/darwinia-dvm.ts, packages/shared/config/network/goerli.ts, packages/shared/config/network/pangoro-dvm.ts
fix s2s v2 validation
direction component balance
=> chore: update eth2 contracts

packages/apps/components/NetworkG6.tsx
=> fix: test chainge g6 graph

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/apps/utils/balance.ts, packages/shared/utils/network/balance/parachain.ts
=> fix: redundant fee & balance & dailyLimit quering

packages/apps/__tests__/fixture/darwin-dvm-crab-dvm.json, packages/apps/__tests__/network.spec.ts, packages/apps/__tests__/record.spec.ts, packages/apps/components/NetworkG6.tsx, packages/apps/hooks/checkSpecVersion.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia-dvm.ts
=> fix(#276): wrong upgrade prompt

packages/apps/components/history/History.tsx, packages/apps/components/widget/TokenOnChain.tsx, packages/shared/config/network/goerli.ts
=> fix(#293, #287): goerli name

packages/shared/config/network/goerli.ts, packages/shared/config/network/pangoro-dvm.ts
=> feat: eth2 support kton transfer

packages/apps/components/form-control/Destination.tsx, packages/apps/components/form-control/SelectTokenModal.tsx
=> feat: simplify token selection

packages/apps/components/form-control/Destination.tsx
=> chore: move calc width to useEffect

packages/apps/bridges/celer/cBridge/CBridge.tsx
=> fix(#299): cbridge validation

packages/apps/bridges/celer/cBridge/CBridge.tsx, packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Destination.tsx, packages/shared/__tests__/helper/balance.spec.ts, packages/shared/utils/helper/balance.ts
=> fix(#317): digits excess

packages/shared/config/network/darwinia.ts, packages/shared/config/network/ethereum.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/ropsten.ts
=> chore: ethv1 offline

packages/shared/config/network/pangolin-dvm.ts, packages/shared/config/network/pangolin.ts, packages/shared/config/network/pangoro-dvm.ts, packages/shared/config/network/pangoro.ts
=> chore: bump panoglin pangoro spec version 210000

packages/apps/components/ethv1/Claim.tsx, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/config/ethv1/constant.ts, packages/apps/pages/claim-tool.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json
=> chore: check ethv1 claim by active account

README.md, packages/apps/bridges/bridges.ts
The problem described in #316 seems not to exist. @ZolaxZola 
Just fix an error due to the console.log
=> fix(#316): bridge down on test net

packages/shared/config/network/karura.ts, packages/shared/config/network/moonriver.ts
=> chore: bump karura moonriver spec version

README.md, packages/apps/bridge.sh, packages/apps/bridges/helix/substrate-dvm/utils/bridge.ts, packages/apps/next.config.js, packages/shared/config/network/darwinia-dvm.ts, packages/shared/config/network/darwinia.ts
=> feat(#339): darwinia-dvm kton transfer

packages/apps/components/CrossChain.tsx, packages/apps/core/bridge.ts
trying reset daily limit to fix #342
=> chore: may be fix 342

packages/apps/bridges/helix/substrateDVM-substrateDVM/utils/bridge-inner.ts
=> fix(#349): substrate-dvm inner fee holding

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/BridgeSelector.tsx, packages/apps/components/widget/CrossChainInfo.tsx, packages/apps/hooks/allowance.tsx, packages/apps/pages/apps.tsx, packages/apps/utils/bridge/bridge.ts
=> chore: remove bridge selector

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx
=> fix(#345): max available balance validate

packages/apps/bridges/xcm/crabParachain-karura/utils/bridge.ts, packages/apps/bridges/xcm/crabParachain-moonriver/utils/bridge.ts, packages/apps/components/form-control/Direction.tsx
=> fix(#346): restore xcm toAmount

packages/apps/components/CrossChain.tsx, packages/apps/components/tx/TransferConfirm.tsx, packages/apps/components/tx/TransferDone.tsx, packages/apps/hooks/tx.tsx, packages/apps/model/component.ts, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/apps/styles/modal.scss, packages/shared/utils/tx/common.tsx
=> feat: confirm done modal 

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/components/history/History.tsx, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/components/widget/account/SelectWalletModal.tsx, packages/apps/hooks/tx.tsx, packages/apps/pages/apps.tsx, packages/apps/pages/transaction/index.tsx, packages/apps/providers/account.tsx, packages/apps/providers/api.tsx, packages/apps/providers/wallet.tsx, packages/shared/__tests__/helper/validator.spec.ts, packages/shared/core/chain.ts, packages/shared/model/storage.ts, packages/shared/utils/helper/url.ts, packages/shared/utils/helper/validator.ts
=> feat: decouple wallet connection with transfer

packages/apps/components/form-control/Direction.tsx
=> fix: storage field validate

packages/apps/components/CrossChain.tsx
=> fix(#360): native token no need to approve

packages/apps/components/history/History.tsx, packages/apps/core/bridge.ts
=> fix: validation

packages/apps/components/history/History.tsx, packages/apps/components/transaction/Detail.tsx, packages/apps/components/transaction/Token.tsx
close #364 ,close #366 , close #368, close #369, close #370
=> fix: some known issues

packages/apps/components/CrossChain.tsx, packages/apps/components/widget/CrossChainInfo.tsx, packages/apps/core/bridge.ts
=> fix: validation and approve

packages/apps/__tests__/bridge.spec.ts, packages/apps/__tests__/components/Bridge.spec.tsx, packages/apps/__tests__/components/__snapshots__/Bridge.spec.tsx.snap, packages/apps/__tests__/path.spec.ts, packages/apps/bridges/helix/substrateDVM-ethereum/utils/bridge.ts, packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/BridgeSelector.tsx, packages/apps/components/form-control/Direction.tsx, packages/apps/components/history/History.tsx, packages/apps/components/history/PendingToRefund.tsx, packages/apps/components/transaction/Bridge.tsx, packages/apps/components/transaction/Detail.tsx, packages/apps/core/bridge.ts, packages/apps/pages/transaction/cbridge/[id].tsx, packages/apps/pages/transaction/eth2/[id].tsx, packages/apps/pages/transaction/s2dvm/[id].tsx, packages/apps/pages/transaction/s2parachain/[id].tsx, packages/apps/pages/transaction/s2s/[id].tsx, packages/apps/pages/transaction/s2sv2/[id].tsx, packages/apps/pages/transaction/xcm/[id].tsx, packages/apps/providers/claim.tsx, packages/apps/utils/bridge/bridge.ts, packages/apps/utils/bridge/predicates.ts, packages/apps/utils/record/path.ts, packages/apps/utils/record/record.ts
Bridge querying may be incorrect if a chain both can be a backing side and issuing side
=> refactor: more accurate bridge finder

packages/apps/__tests__/components/__snapshots__/SourceTx.spec.tsx.snap, packages/apps/components/form-control/Destination.tsx, packages/apps/components/transaction/Detail.tsx, packages/apps/components/transaction/SourceTx.tsx, packages/apps/components/transaction/TargetTx.tsx, packages/apps/components/transaction/Token.tsx, packages/apps/styles/apps.scss
=> fix(#382): hash link error

packages/apps/components/history/History.tsx, packages/apps/providers/account.tsx, packages/shared/model/storage.ts
Can not memory Polkadot's active account
=> fix: polkadot account memory

packages/apps/bridges/helix/crabDVM-darwiniaDVM/utils/bridge.ts, packages/apps/public/locales/zh/common.json, packages/shared/components/widget/BestNumber.tsx
=> chore: label

packages/apps/bridges/cbridge/cBridge/utils/bridge.ts, packages/apps/bridges/helix/crabDVM-darwiniaDVM/utils/bridge.ts, packages/apps/components/history/PendingToRefund.tsx, packages/apps/utils/bridge/bridge.ts, packages/shared/config/network/arbitrum.ts, packages/shared/config/network/astar.ts, packages/shared/config/network/avalanche.ts, packages/shared/config/network/bsc.ts, packages/shared/config/network/ethereum.ts, packages/shared/config/network/goerli.ts, packages/shared/config/network/heco.ts, packages/shared/config/network/optimism.ts, packages/shared/config/network/polygon.ts, packages/shared/config/network/ropsten.ts, packages/shared/utils/helper/address.ts
=> chore: add symbol compare

packages/apps/components/transaction/TxStatus.tsx, packages/apps/components/widget/CrossChainInfo.tsx, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json
=> fix(#402): countdown time

packages/shared/utils/network/balance/parachain.ts
=> fix: parachain balance querying use wss provider

packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/crab.ts
=> chore: update crab spec

packages/apps/bridges/helix/substrateDVM-substrateParachain/utils/bridge.ts, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/providers/api.tsx, packages/shared/model/network/network.ts, packages/shared/model/storage.ts, packages/shared/utils/connection/connection.tsx, packages/shared/utils/connection/metamask.ts, packages/shared/utils/connection/polkadot.ts, packages/shared/utils/tx/polkadot.ts
=> feat: memo favorite wallet

packages/apps/providers/wallet.tsx
=> fix(#426): limit incorrect wallet memo connect

packages/apps/providers/account.tsx, packages/apps/providers/api.tsx
=> fix(#430): flow the departure connnection account format

packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/providers/api.tsx
=> fix(#426): can not find config error

packages/apps/components/transaction/TxStatus.tsx
=> fix(#413): update claim tip

packages/apps/components/CrossChain.tsx, packages/apps/components/form-control/Direction.tsx
=> fix(#415): cBridge tx params validation

packages/apps/components/CrossChain.tsx
=> fix(#416): validate connected chain before approve

packages/apps/bridges/helix/substrate-dvm/model/bridge.ts, packages/apps/bridges/helix/substrate-substrateDVM/model/bridge.ts, packages/apps/bridges/helix/substrate-substrateParachain/model/bridge.ts, packages/apps/bridges/helix/substrateDVM-ethereum/model/bridge.ts, packages/apps/bridges/helix/substrateDVM-substrateParachain/model/bridge.ts, packages/apps/bridges/xcm/crabParachain-karura/model/bridge.ts, packages/apps/bridges/xcm/crabParachain-moonriver/model/bridge.ts, packages/apps/global.d.ts, packages/apps/model/tx.ts, packages/shared/global.d.ts, packages/shared/utils/connection/connection.tsx, packages/shared/utils/connection/polkadot.ts, packages/shared/utils/tx/polkadot.ts
=> fix(#435): remove web3Enable

packages/apps/bridges/cbridge/cBridge/utils/bridge.ts, packages/apps/components/CrossChain.tsx, packages/apps/components/widget/Connecting.tsx, packages/apps/components/widget/Wifi.tsx, packages/apps/components/widget/account/ActiveAccount.tsx, packages/apps/core/bridge.ts, packages/apps/public/locales/en/common.json, packages/apps/public/locales/zh/common.json, packages/apps/styles/loading.scss
=> fix(#304): add validator on bridge subclass

packages/apps/styles/apps.scss, packages/shared/config/network/karura.ts, packages/shared/config/network/moonriver.ts, packages/shared/utils/connection/entrance.ts
=> chore: bump moonriver karura spec version

packages/apps/components/history/History.tsx
=> fix(#424): reset paginator when filter changed

packages/apps/bridges/cbridge/cBridge/utils/bridge.ts
=> fix: cbridge min transfer amount

packages/apps/bridges/xcm/crabParachain-moonriver/utils/bridge.ts
=> fix(#467): missing flag during burn xcCRAB between crab and moonriver

packages/apps/bridges/cbridge/cBridge/utils/bridge.ts
=> fix(#457): cBridage allowance use specific provider

packages/apps/__tests__/record.spec.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia-dvm.ts
=> pause s2s wring token

packages/apps/bridges/helix/darwiniaDVM-crabDVM/config/backing.json, packages/apps/bridges/helix/darwiniaDVM-crabDVM/config/mappingToken.json, packages/apps/bridges/helix/darwiniaDVM-crabDVM/utils/bridge.ts, packages/shared/config/network/crab-dvm.ts, packages/shared/config/network/darwinia-dvm.ts
=> support native ring

packages/apps/__tests__/bridge.spec.ts, packages/apps/__tests__/network.spec.ts, packages/apps/bridges/helixlp/arbitrum-ethereum/config/bridge.ts, packages/apps/bridges/l1tol2/ethereum-arbitrum/config/bridge.ts, packages/apps/config/bridge.ts, packages/shared/config/network/arbitrum.ts, packages/shared/config/network/ethereum.ts
Add arbitrum mainnet LnBridge: arbitrum -> ethereum
Add arbitrum original L1 to L2 bridge: ethereum -> arbitrum
=> arbitrum mainnet bridge

packages/apps/bridge.sh
=> chore: update and fix some issues

packages/apps/components/form-control/Direction.tsx, packages/apps/utils/bridge/bridge.ts
=> fix: bridge selection on initialization

packages/apps/bridges/lnbridge/lnbridge/utils/bridge.ts
=> Remove LnBridge daily limit

packages/apps/components/CrossChain.tsx, packages/apps/components/bridge/Bridge.tsx, packages/apps/components/widget/CrossChainInfo.tsx, packages/apps/model/component.ts
=> Fix fee loading all the time

packages/shared/components/Footer.tsx
=> Entrance to the testnet or mainnet

packages/apps/.env.test, packages/apps/src/bridges/lnbridge-default.ts, packages/apps/src/config/chains/ethereum.ts
Preview: https://helix-apps-qmp97rqc9-itering.vercel.app/
=> Change to LnBridge for transfering RING from Ethereum to Arbitrum

packages/apps/src/bridges/helixbridge-dvmdvm.ts, packages/apps/src/bridges/helixbridge-dvmevm.ts, packages/apps/src/components/record-detail.tsx, packages/apps/src/config/chains/arbitrum.ts, packages/apps/src/config/chains/darwinia.ts, packages/apps/src/config/chains/ethereum.ts, packages/apps/src/config/chains/mantle.ts, packages/apps/src/types/token.ts
=> Support USDT Arbitrum<>Mantle crossing

packages/apps/src/components/balance-input.tsx, packages/apps/src/components/transfer.tsx
=> Improve dynamic font size

packages/apps/src/components/balance-input.tsx
=> Fix manage relayer crash

packages/apps/src/components/chain-select.tsx, packages/apps/src/config/chains/arbitrum.ts, packages/apps/src/config/chains/bsc.ts, packages/apps/src/config/chains/linea.ts
=> Support Linea USDT

src/components/fee-rate-input.tsx, src/components/modals/relayer-manage-v3-modal.tsx, src/components/relayer-register-v3.tsx, src/config/constant.ts, src/utils/misc.ts
=> fix: lnv3 liquidity fee rate max limit

src/bridges/lnbridge-v3.ts, src/components/modals/relayer-manage-v3-modal.tsx, src/components/relayer-register-v3.tsx, src/hooks/index.ts, src/hooks/use-liquidity-withdraw-fee-params.ts, src/providers/relayer-provider-v3.tsx
=> Fix fee rate disable check and extParams of liquidity withdraw

src/bridges/xtoken-v3.ts, src/config/chains/crab.ts, src/config/chains/darwinia.ts, src/types/bridge.ts, src/utils/bridge.ts, src/utils/misc.ts
=> Darwinia<>Crab xToken

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml, .github/workflows/deploy-stg.yml
=> revert: ci remove

.github/workflows/deploy-dev.yml, src/app/relayer/page.tsx, src/components/chain-identity.tsx, src/components/footer.tsx, src/components/header.tsx, src/components/lnrelayers-overview.tsx, src/components/modals/relayer-manage-modal.tsx, src/components/modals/relayer-manage-v3-modal.tsx, src/components/records-table.tsx, src/components/relayer-allowance.tsx, src/components/relayer-balance.tsx, src/components/relayer-penalty.tsx, src/components/relayer-total-liquidity.tsx, src/components/relayers-manage.tsx, src/components/relayers-table.tsx, src/config/gql.ts, src/hooks/index.ts, src/hooks/use-all-allowance.ts, src/hooks/use-allowance.ts, src/types/graphql.ts, src/ui/pagination.tsx, src/ui/segmented-tabs.tsx, src/ui/table.tsx
=> Improve relayer dashboard

src/config/chains/crab.ts, src/config/chains/darwinia.ts
=> Hide Darwinia<>Crab and CRAB LnBridge

src/components/icons/checked.tsx, src/components/transfer-chain-section.tsx, src/components/transfer-section-title.tsx, src/ui/copy-icon.tsx
=> Token information tooltips

src/bridges/base.ts, src/components/transaction-status.tsx
=> Update time to contact for transaction

src/app/globals.css, src/components/chain-select.tsx, src/components/modals/transfer-modal-v2.tsx, src/components/record-detail.tsx, src/components/transfer-amount-input.tsx, src/components/transfer-amount-section.tsx, src/components/transfer-chain-select.tsx, src/components/transfer-information-section.tsx, src/components/transfer-information.tsx, src/components/transfer-v2.tsx, src/components/user.tsx, src/components/withdrawable-liquidities-select.tsx
=> Improve information display

src/components/transfer-amount-input.tsx, src/components/transfer-amount-section.tsx, src/components/transfer-chain-section.tsx, src/components/transfer-chain-select.tsx, src/components/transfer-information.tsx, src/components/transfer-token-select.tsx, src/components/transfer-v2.tsx, src/config/gql.ts, src/hooks/index.ts, src/hooks/use-max-transfer.ts, src/providers/rainbow-provider.tsx, src/types/graphql.ts, src/ui/tooltip.tsx
=> Support max-transfer input

src/bridges/lnbridge-v3.ts, src/config/chains/base-sepolia.ts, src/config/chains/index.ts, src/config/chains/sepolia.ts, src/types/chain.ts, src/utils/chain.ts
=> Support Base Sepolia
